spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/coredb}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
app:
  jwt:
    secret: ${APP_JWT_SECRET:change-me-please}
    expiration-ms: ${APP_JWT_EXP_MS:3600000} # 1 hora por defecto