spring:
  datasource:
    # Opción 1: Construir URL desde componentes (como Railway)
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:coredb}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:admin}

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:8080}

mercadopago:
  access-token: ${MERCADOPAGO_ACCESS_TOKEN:APP_USR-858347681559407-101620-5af417c833576f423e24c51d1b7e2ae8-2929598981}
  public-key: ${MERCADOPAGO_PUBLIC_KEY:APP_USR-df73fee1-9191-4a9e-94b6-887bb0f9684a}
  webhook-secret: ${MERCADOPAGO_WEBHOOK_SECRET:f5554dacf8117ffca8a1356a2e76d77665651992d2482af0085be13a67bd75b3}
  webhook-url: ${MERCADOPAGO_WEBHOOK_URL:https://jalisa-unsensualistic-unfemininely.ngrok-free.dev/api/payments/webhook/mercadopago}
  success-url: ${MERCADOPAGO_SUCCESS_URL:https://jalisa-unsensualistic-unfemininely.ngrok-free.dev/api/payments/success}
  failure-url: ${MERCADOPAGO_FAILURE_URL:https://jalisa-unsensualistic-unfemininely.ngrok-free.dev/api/payments/failure}
  pending-url: ${MERCADOPAGO_PENDING_URL:https://jalisa-unsensualistic-unfemininely.ngrok-free.dev/api/payments/pending}

app:
  jwt:
    secret: ${APP_JWT_SECRET:change-me-please}
    expiration-ms: ${APP_JWT_EXP_MS:3600000}