spring:
  datasource:
    # Opción 1: Construir URL desde componentes (como Railway)
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:coredb}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${APP_JWT_SECRET:change-me-please}
    expiration-ms: ${APP_JWT_EXP_MS:3600000}